GET http://localhost:3001/token
Accept: application/json

###

GET http://localhost:3001/token?size=100&limit=1
Accept: application/json

###

GET http://localhost:3001/token?size=10&page=1&limit=1
Accept: application/json

