apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default-ingress
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.carbon.xyz #staging.api.carbon.xyz
    secretName: default-tls-secret
  rules:
  - host: api.carbon.xyz #staging.api.carbon.xyz
    http:
      paths:
      - backend:
          serviceName: api
          servicePort: 3001
