apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/issuer: letsencrypt-prod
spec:
  tls:
    - secretName: default-tls-secret
      hosts:
        - carbon-api.miguel-franken.com
  defaultBackend:
    service:
      name: api
      port:
        number: 3001

