apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - secretName: default-tls-secret
      hosts:
        - carbon-api.miguel-franken.com
#  tls:
#  - hosts:
#    - carbon-api.miguel-franken.com
#    secretName: default-tls-secret
#  rules:
#  - host: carbon-api.miguel-franken.com
#    http:
#      paths:
#      - backend:
#          serviceName: api
#          servicePort: 3001

  defaultBackend:
    service:
      name: api
      port:
        number: 3001

