apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
  namespace: default
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"auth":"<BASE_64_ENCODED_PAT>"}}}'
